CREATE DATABASE [bankdb]
GO

USE [bankdb]
CREATE TABLE [bank]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[name] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE [city]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[name] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE [branch]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[bankId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [bank] ([id]) NOT NULL,
	[cityId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [city] ([id]) NOT NULL,
	[name] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE [status]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[name] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE [client]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[statusId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [status] ([id]) NOT NULL,
	[name] NVARCHAR(MAX) NOT NULL,
	[surname] NVARCHAR(MAX) NOT NULL
)

CREATE TABLE [account]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[clientId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [client] ([id]) NOT NULL,
	[bankId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [bank] ([id]) NOT NULL UNIQUE ([clientId], [bankId]),
	[totalBalance] INT NOT NULL DEFAULT 0
)

CREATE TABLE [card]
(
    [id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newid(),
	[accountId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [account] ([id]) NOT NULL,
	[balance] INT NOT NULL DEFAULT 0
)